version: '3.8'

services:
  # Local MySQL Instance for Development
  mysql:
    image: mysql:8.0
    container_name: nocodb-mysql-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nocodb_portal
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # Database Management Interface
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nocodb-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql
